/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { Linkific } from "./Linkific";
import { LinkificCountArgs } from "./LinkificCountArgs";
import { LinkificFindManyArgs } from "./LinkificFindManyArgs";
import { LinkificFindUniqueArgs } from "./LinkificFindUniqueArgs";
import { DeleteLinkificArgs } from "./DeleteLinkificArgs";
import { LinkificService } from "../linkific.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Linkific)
export class LinkificResolverBase {
  constructor(
    protected readonly service: LinkificService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Linkific",
    action: "read",
    possession: "any",
  })
  async _linkificsMeta(
    @graphql.Args() args: LinkificCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Linkific])
  @nestAccessControl.UseRoles({
    resource: "Linkific",
    action: "read",
    possession: "any",
  })
  async linkifics(
    @graphql.Args() args: LinkificFindManyArgs
  ): Promise<Linkific[]> {
    return this.service.linkifics(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Linkific, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Linkific",
    action: "read",
    possession: "own",
  })
  async linkific(
    @graphql.Args() args: LinkificFindUniqueArgs
  ): Promise<Linkific | null> {
    const result = await this.service.linkific(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Linkific)
  @nestAccessControl.UseRoles({
    resource: "Linkific",
    action: "delete",
    possession: "any",
  })
  async deleteLinkific(
    @graphql.Args() args: DeleteLinkificArgs
  ): Promise<Linkific | null> {
    try {
      return await this.service.deleteLinkific(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
